#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD5F974219CA2E722 (tchemit@codehaus.org)
#
Name     : mvn-mojo-signature
Version  : 1.0
Release  : 2
URL      : https://repo1.maven.org/maven2/org/codehaus/mojo/signature/java17/1.0/java17-1.0-source-release.zip
Source0  : https://repo1.maven.org/maven2/org/codehaus/mojo/signature/java17/1.0/java17-1.0-source-release.zip
Source1  : https://repo1.maven.org/maven2/org/codehaus/mojo/signature/java17/1.0/java17-1.0.pom
Source2  : https://repo1.maven.org/maven2/org/codehaus/mojo/signature/java17/1.0/java17-1.0.signature
Source99 : https://repo1.maven.org/maven2/org/codehaus/mojo/signature/java17/1.0/java17-1.0-source-release.zip.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-mojo-signature-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-mojo-signature package.
Group: Data

%description data
data components for the mvn-mojo-signature package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/signature/java17/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/signature/java17/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/signature/java17/1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/signature/java17/1.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/mojo/signature/java17/1.0/java17-1.0.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/signature/java17/1.0/java17-1.0.signature
